name: Java CI with Gradle

on:
  push:
    # Sequence of patterns matched against refs/heads
    branches:    
      - 'releases/**'
    # Sequence of patterns matched against refs/tags
    tags:        
      - '*'
  workflow_dispatch:
    inputs:
      build_target:
        description: "Specify the build target (optional, default runs all jobs)"
        required: false
        default: "all"  
        type: choice
        options:
          - "all"  # "all" 表示运行所有任务
          - "build_folia"
          - "build_bukkit"
          - "build_bungeecord_velocity"
          - "build_fabric_1_16_5"
          - "build_fabric_1_18_2"
          - "build_fabric_1_19_2"
          - "build_fabric_1_20"
          - "build_fabric_1_20_2"
          - "build_fabric_1_20_6"
          - "build_fabric_1_21"
          - "build_forge_1_7_10"
          - "build_forge_1_12_2"
          - "build_forge_1_16_5"
          - "build_forge_1_18_2"
          - "build_forge_1_19_2"
          - "build_forge_1_20"
          - "build_neoforge_1_20_4"
          - "build_neoforge_1_20_5"
          - "build_neoforge_1_21"

jobs:
  build_folia:
    if: ${{ inputs.build_target == 'all' || inputs.build_target == 'build_folia' }}
    runs-on: windows-latest
    permissions:
      contents: read
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v3 # v3.1.0
    - name: build
      shell: cmd
      run: |
        link.cmd && cd folia && gradlew shadowJar
    - name: update
      uses: actions/upload-artifact@v4
      with:
        name: "allmusic_server_folia"
        path: build/libs/

  build_bukkit:
    if: ${{ inputs.build_target == 'all' || inputs.build_target == 'build_bukkit' }}
    runs-on: windows-latest
    permissions:
      contents: read
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 8
      uses: actions/setup-java@v4
      with:
        java-version: '8'
        distribution: 'temurin'
    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v3 # v3.1.0
    - name: build
      shell: cmd
      run: |
        link.cmd && cd server && gradlew shadowJar
    - name: update
      uses: actions/upload-artifact@v4
      with:
        name: "allmusic_server_bukkit"
        path: build/libs/

  build_bungeecord_velocity:
    if: ${{ inputs.build_target == 'all' || inputs.build_target == 'build_bungeecord_velocity' }}
    runs-on: windows-latest
    permissions:
      contents: read
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 8
      uses: actions/setup-java@v4
      with:
        java-version: '8'
        distribution: 'temurin'
    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v3 # v3.1.0
    - name: build
      shell: cmd
      run: |
        link.cmd && cd server_top && gradlew shadowJar
    - name: update
      uses: actions/upload-artifact@v4
      with:
        name: "allmusic_server_bungeecord_velocity"
        path: build/libs/

  build_fabric_1_16_5:
    if: ${{ inputs.build_target == 'all' || inputs.build_target == 'build_fabric_1_16_5' }}
    runs-on: windows-latest
    permissions:
      contents: read
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v3 # v3.1.0
    - name: build
      shell: cmd
      run: |
        link.cmd && cd fabric_1_16_5 && gradlew build
    - name: update
      uses: actions/upload-artifact@v4
      with:
        name: "allmusic_server_fabric_1_16_5"
        path: build/libs/

  build_fabric_1_18_2:
    if: ${{ inputs.build_target == 'all' || inputs.build_target == 'build_fabric_1_18_2' }}
    runs-on: windows-latest
    permissions:
      contents: read
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v3 # v3.1.0
    - name: build
      shell: cmd
      run: |
        link.cmd && cd fabric_1_18_2 && gradlew build
    - name: update
      uses: actions/upload-artifact@v4
      with:
        name: "allmusic_server_fabric_1_18_2"
        path: build/libs/

  build_fabric_1_19_2:
    if: ${{ inputs.build_target == 'all' || inputs.build_target == 'build_fabric_1_19_2' }}
    runs-on: windows-latest
    permissions:
      contents: read
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v3 # v3.1.0
    - name: build
      shell: cmd
      run: |
        link.cmd && cd fabric_1_19_2 && gradlew build
    - name: update
      uses: actions/upload-artifact@v4
      with:
        name: "allmusic_server_fabric_1_19_2"
        path: build/libs/

  build_fabric_1_20:
    if: ${{ inputs.build_target == 'all' || inputs.build_target == 'build_fabric_1_20' }}
    runs-on: windows-latest
    permissions:
      contents: read
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v3 # v3.1.0
    - name: build
      shell: cmd
      run: |
        link.cmd && cd fabric_1_20 && gradlew build
    - name: update
      uses: actions/upload-artifact@v4
      with:
        name: "allmusic_server_fabric_1_20"
        path: build/libs/

  build_fabric_1_20_2:
    if: ${{ inputs.build_target == 'all' || inputs.build_target == 'build_fabric_1_20_2' }}
    runs-on: windows-latest
    permissions:
      contents: read
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v3 # v3.1.0
    - name: build
      shell: cmd
      run: |
        link.cmd && cd fabric_1_20_2 && gradlew build
    - name: update
      uses: actions/upload-artifact@v4
      with:
        name: "allmusic_server_fabric_1_20_2"
        path: build/libs/

  build_fabric_1_20_6:
    if: ${{ inputs.build_target == 'all' || inputs.build_target == 'build_fabric_1_20_6' }}
    runs-on: windows-latest
    permissions:
      contents: read
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v3 # v3.1.0
    - name: build
      shell: cmd
      run: |
        link.cmd && cd fabric_1_20_6 && gradlew build
    - name: update
      uses: actions/upload-artifact@v4
      with:
        name: "allmusic_server_fabric_1_20_6"
        path: build/libs/

  build_fabric_1_21:
    if: ${{ inputs.build_target == 'all' || inputs.build_target == 'build_fabric_1_21' }}
    runs-on: windows-latest
    permissions:
      contents: read
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v3 # v3.1.0
    - name: build
      shell: cmd
      run: |
        link.cmd && cd fabric_1_21 && gradlew build
    - name: update
      uses: actions/upload-artifact@v4
      with:
        name: "allmusic_server_fabric_1_21"
        path: build/libs/

  build_forge_1_7_10:
    if: ${{ inputs.build_target == 'all' || inputs.build_target == 'build_forge_1_7_10' }}
    runs-on: windows-latest
    permissions:
      contents: read
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 8
      uses: actions/setup-java@v4
      with:
        java-version: '8'
        distribution: 'temurin'
    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v3 # v3.1.0
    - name: build
      shell: cmd
      run: |
        link.cmd && cd forge_1_7_10 && gradlew build
    - name: update
      uses: actions/upload-artifact@v4
      with:
        name: "allmusic_server_forge_1_7_10"
        path: build/libs/

  build_forge_1_12_2:
    if: ${{ inputs.build_target == 'all' || inputs.build_target == 'build_forge_1_12_2' }}
    runs-on: windows-latest
    permissions:
      contents: read
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 8
      uses: actions/setup-java@v4
      with:
        java-version: '8'
        distribution: 'temurin'
    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v3 # v3.1.0
    - name: build
      shell: cmd
      run: |
        link.cmd && cd forge_1_12_2 && gradlew build
    - name: update
      uses: actions/upload-artifact@v4
      with:
        name: "allmusic_server_forge_1_12_2"
        path: build/libs/

  build_forge_1_16_5:
    if: ${{ inputs.build_target == 'all' || inputs.build_target == 'build_forge_1_16_5' }}
    runs-on: windows-latest
    permissions:
      contents: read
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 8
      uses: actions/setup-java@v4
      with:
        java-version: '8'
        distribution: 'temurin'
    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v3 # v3.1.0
    - name: build
      shell: cmd
      run: |
        link.cmd && cd forge_1_16_5 && gradlew build
    - name: update
      uses: actions/upload-artifact@v4
      with:
        name: "allmusic_server_forge_1_16_5"
        path: build/libs/

  build_forge_1_18_2:
    if: ${{ inputs.build_target == 'all' || inputs.build_target == 'build_forge_1_18_2' }}
    runs-on: windows-latest
    permissions:
      contents: read
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v3 # v3.1.0
    - name: build
      shell: cmd
      run: |
        link.cmd && cd forge_1_18_2 && gradlew build
    - name: update
      uses: actions/upload-artifact@v4
      with:
        name: "allmusic_server_forge_1_18_2"
        path: build/libs/

  build_forge_1_19_2:
    if: ${{ inputs.build_target == 'all' || inputs.build_target == 'build_forge_1_19_2' }}
    runs-on: windows-latest
    permissions:
      contents: read
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v3 # v3.1.0
    - name: build
      shell: cmd
      run: |
        link.cmd && cd forge_1_19_2 && gradlew build
    - name: update
      uses: actions/upload-artifact@v4
      with:
        name: "allmusic_server_forge_1_19_2"
        path: build/libs/

  build_forge_1_20:
    if: ${{ inputs.build_target == 'all' || inputs.build_target == 'build_forge_1_20' }}
    runs-on: windows-latest
    permissions:
      contents: read
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v3 # v3.1.0
    - name: build
      shell: cmd
      run: |
        link.cmd && cd forge_1_20 && gradlew build
    - name: update
      uses: actions/upload-artifact@v4
      with:
        name: "allmusic_server_forge_1_20"
        path: build/libs/

  build_neoforge_1_20_4:
    if: ${{ inputs.build_target == 'all' || inputs.build_target == 'build_neoforge_1_20_4' }}
    runs-on: windows-latest
    permissions:
      contents: read
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v3 # v3.1.0
    - name: build
      shell: cmd
      run: |
        link.cmd && cd neoforge_1_20_4 && gradlew build
    - name: update
      uses: actions/upload-artifact@v4
      with:
        name: "allmusic_server_neoforge_1_20_4"
        path: build/libs/

  build_neoforge_1_20_5:
    if: ${{ inputs.build_target == 'all' || inputs.build_target == 'build_neoforge_1_20_5' }}
    runs-on: windows-latest
    permissions:
      contents: read
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v3 # v3.1.0
    - name: build
      shell: cmd
      run: |
        link.cmd && cd neoforge_1_20_5 && gradlew build
    - name: update
      uses: actions/upload-artifact@v4
      with:
        name: "allmusic_server_neoforge_1_20_5"
        path: build/libs/

  build_neoforge_1_21:
    if: ${{ inputs.build_target == 'all' || inputs.build_target == 'build_neoforge_1_21' }}
    runs-on: windows-latest
    permissions:
      contents: read
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v3 # v3.1.0
    - name: build
      shell: cmd
      run: |
        link.cmd && cd neoforge_1_21 && gradlew build
    - name: update
      uses: actions/upload-artifact@v4
      with:
        name: "allmusic_server_neoforge_1_21"
        path: build/libs/
